# This is a basic workflow to help you get started with Actions

name: Ragu
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install yarn
    - run: yarn --cwd ragu-server
      env:
        CI: true
    - run: yarn --cwd ragu-dom
      env:
        CI: true
    - run: yarn install
      env:
        CI: true
    - run: yarn test
      env:
        CI: true
    - run: yarn --cwd ragu-server add webpack@4 @types/webpack
      env:
        CI: true
    - run: yarn --cwd ragu-server jest --runTestsByPath testing/components-compiler.spec.ts
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
